{
 "title": "Vendas Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "VENDAS TIME SERIES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "select DATE(data) as 'time', sum(valor) as \"Valor em R$\" from vendas \nwhere $__timeFilter(data)\ngroup by DATE(data)\n"
    }
   ]
  },
  {
   "title": "QUANTIDADE DE ERROS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "SELECT\n  CAST(\n    CONVERT_TZ(\n      DATE_FORMAT(data, '%Y-%m-%d %H:%i:0'),\n      '+00:00',\n      '+03:00'\n    ) AS DATETIME\n  ) AS time,\n  COUNT(*) AS count\nFROM\n  erros\nGROUP BY\n  time\nORDER BY\n  time desc;"
    }
   ]
  },
  {
   "title": "ERROS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "select\n  CAST(\n    CONVERT_TZ(\n      DATE_FORMAT(data, '%Y-%m-%d %H:%i:%s'),\n      '+00:00',\n      '+03:00'\n    ) AS DATETIME\n  ) AS time,\n  descricao\nfrom\n  erros\nwhere\n  $__timeFilter(data)\norder by\n  data desc"
    }
   ]
  },
  {
   "title": "Meta",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "select sum(valor) / 10000 * 100 AS `percentage` from vendas v \nWHERE MONTH(data) = MONTH(CURRENT_DATE())\nAND YEAR(data) = YEAR(CURRENT_DATE()) "
    }
   ]
  },
  {
   "title": "Vendas por dia",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "select DATE(data), sum(valor) as \"Valor em R$\" from vendas \nwhere $__timeFilter(data)\ngroup by DATE(data)\n\n\n"
    }
   ]
  },
  {
   "title": "Vendas",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "select * from db.vendas\nwhere $__timeFilter(data)\norder by data desc"
    }
   ]
  }
 ]
}